//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXV6_Screenshot_Grabber.Locale.DynamicLabels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DynamicLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DynamicLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXV6_Screenshot_Grabber.Locale.DynamicLabels.DynamicLabels", typeof(DynamicLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Narod.
        /// </summary>
        public static string Main_AuthorLabel {
            get {
                return ResourceManager.GetString("Main_AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit:.
        /// </summary>
        public static string Main_Commit {
            get {
                return ResourceManager.GetString("Main_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narod&apos;s FFXV (Comrades) Screenshot Grabber.
        /// </summary>
        public static string Main_ComradesTitle {
            get {
                return ResourceManager.GetString("Main_ComradesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button attempts to automatically locate your screenshot folder..
        /// </summary>
        public static string Main_DetectFolderTooltip {
            get {
                return ResourceManager.GetString("Main_DetectFolderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must disable Realtime mode to change the folder location..
        /// </summary>
        public static string Main_DisableRealtimeWarning {
            get {
                return ResourceManager.GetString("Main_DisableRealtimeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narod&apos;s FFXV Screenshot Grabber.
        /// </summary>
        public static string Main_FFXVSG {
            get {
                return ResourceManager.GetString("Main_FFXVSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform: .
        /// </summary>
        public static string Main_Platform {
            get {
                return ResourceManager.GetString("Main_Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshots: .
        /// </summary>
        public static string Main_Screenshots {
            get {
                return ResourceManager.GetString("Main_Screenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button allows you to change the current screenshot directory..
        /// </summary>
        public static string Main_SelectFolderTooltip {
            get {
                return ResourceManager.GetString("Main_SelectFolderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot taken on .
        /// </summary>
        public static string Main_SnapshotTakenOn {
            get {
                return ResourceManager.GetString("Main_SnapshotTakenOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temp.
        /// </summary>
        public static string Main_Temp {
            get {
                return ResourceManager.GetString("Main_Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narod&apos;s FFXV Screenshot Grabber.
        /// </summary>
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available: .
        /// </summary>
        public static string Main_UpdateAvailable {
            get {
                return ResourceManager.GetString("Main_UpdateAvailable", resourceCulture);
            }
        }
    }
}
