//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXV6_Screenshot_Grabber.Locale.Dialogs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dialogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialogs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXV6_Screenshot_Grabber.Locale.Dialogs.Dialogs", typeof(Dialogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFXV screenshot folder given does not exist, or not enough permissions to access!.
        /// </summary>
        public static string Body_Error_InvalidScreenshotFolder {
            get {
                return ResourceManager.GetString("Body_Error_InvalidScreenshotFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No screenshot folder specified. You must select a folder! Closing....
        /// </summary>
        public static string Body_Error_NoScreenshotFolder {
            get {
                return ResourceManager.GetString("Body_Error_NoScreenshotFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to automatically detect FFXV folder! Please manually search for it!.
        /// </summary>
        public static string Body_Error_UnableDetectBase {
            get {
                return ResourceManager.GetString("Body_Error_UnableDetectBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to automatically detect FFXV Comrades folder! Please manually search for it!.
        /// </summary>
        public static string Body_Error_UnableDetectComrades {
            get {
                return ResourceManager.GetString("Body_Error_UnableDetectComrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save screenshots. Please select a folder with some screenshots in to save..
        /// </summary>
        public static string Body_Error_UnableToSaveMulti {
            get {
                return ResourceManager.GetString("Body_Error_UnableToSaveMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save screenshot. Please select a screenshot to preview &amp; save first..
        /// </summary>
        public static string Body_Error_UnableToSaveSingle {
            get {
                return ResourceManager.GetString("Body_Error_UnableToSaveSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the folder containing your FFXV screenshots....
        /// </summary>
        public static string Body_Info_SelectFFXVScreenshotFolder {
            get {
                return ResourceManager.GetString("Body_Info_SelectFFXVScreenshotFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the folder you wish to watch for screenshots....
        /// </summary>
        public static string Body_Info_SelectRealtimeFolder {
            get {
                return ResourceManager.GetString("Body_Info_SelectRealtimeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update to Narod&apos;s FFXV Screenshot Grabber is available, do you wish to download the update?.
        /// </summary>
        public static string Body_Info_UpdateAvailable {
            get {
                return ResourceManager.GetString("Body_Info_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a screenshot to preview first!.
        /// </summary>
        public static string Body_Warn_SelectPreviewScreenshot {
            get {
                return ResourceManager.GetString("Body_Warn_SelectPreviewScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid folder selected!.
        /// </summary>
        public static string Title_Error_InvalidScreenshotFolder {
            get {
                return ResourceManager.GetString("Title_Error_InvalidScreenshotFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to locate folder!.
        /// </summary>
        public static string Title_Error_UnableDetectBase {
            get {
                return ResourceManager.GetString("Title_Error_UnableDetectBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to locate folder!.
        /// </summary>
        public static string Title_Error_UnableDetectComrades {
            get {
                return ResourceManager.GetString("Title_Error_UnableDetectComrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid folder!.
        /// </summary>
        public static string Title_Error_UnableToSaveMulti {
            get {
                return ResourceManager.GetString("Title_Error_UnableToSaveMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a screenshot!.
        /// </summary>
        public static string Title_Error_UnableToSaveSingle {
            get {
                return ResourceManager.GetString("Title_Error_UnableToSaveSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narod&apos;s FFXV Screenshot Grabber - Update Available.
        /// </summary>
        public static string Title_Info_UpdateAvailable {
            get {
                return ResourceManager.GetString("Title_Info_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a screenshot!.
        /// </summary>
        public static string Title_Warn_SelectPreviewScreenshot {
            get {
                return ResourceManager.GetString("Title_Warn_SelectPreviewScreenshot", resourceCulture);
            }
        }
    }
}
